### ISSUE TITLE
include links to bugs covering changes pushed out

### ISSUE THREAD

**Issue by willkg** [willkg/socorro-release#35]
It'd be good to include links to bugs and maybe the bug summaries covering the changes that were pushed out in a release.

**Comment by biancadanforth** [comment]
Where would these links show up, in stdout from the release script? (Aside: I recall most people's terminals actually create links from the terminal, which I had wanted to look into...)

**Comment by willkg** [comment]
When we call the `make-bug` subcommand, `release.py` generates a list of commits that will be deployed. Then it generates a url to create a bug a description that includes the list of commits.

When we create a commit in git, our convention is to include the bug number at the beginning of the commit summary. Because of that, when `release.py` lists all the commits, there are a bunch of bugs related to the commits, but because fixing a bug may require multiple commits and even multiple PRs, it'd help to have a list of all the bugs referenced in commits as a separate summary after the commits summary.

I was thinking something like this:

```
>> Creating deploy bug...
>>> Summary
socorro-release-test deploy: 2024.02.26

>>> Description
We want to do a deploy for `socorro-release-test` tagged `2024.02.26`.

It consists of the following commits:

`8ec7746`: Remove setup.cfg (willkg)
`15e8ca0`: bug 111111: add prod/stage crash-stats urls (willkg)
`9dd9cd6`: bug 1868132: update scripts (FAKE BUG) (willkg)
`6ad421d`: bug 222222: Update release.py (willkg)
`1d9e10b`: Update release.py script (willkg)
`5fc38f7`: support https (willkg)
`76e688e`: Update release.py (willkg)
`99f4a83`: Update release.py (willkg)
`92c4ce2`: bug 1111111: update release.py (willkg)
`a13b982`: bug 1231234: a second commit with a bug (willkg)
`8c52e28`: bug 1111111: second commit for one bug (willkg)
`fb7cd5f`: bug 1111111: another commit (willkg)
`01fac85`: 1231234: another commit (willkg)

Bugs referenced:

* bug #111111
* bug #1111111
* bug #1231234
* bug #1868132
* bug #222222
```

This is only generated in the `make-bug` command, so we want the format of the bugs to work with Bugzilla autolinking. Because it's an ordered set of bug numbers, we don't have think about duplicates. Further, Bugzilla will denote whether the bugs are resolved or not and if you hover over them, it'll print out the bug summary.
